item{
    id: 1
    name: '2h'
}

item{
    id: 2
    name: '3h'
}

item{
    id: 3
    name: '4h'
}

item{
    id: 4
    name: '5h'
}

item{
    id: 5
    name: '6h'
}

item{
    id: 6
    name: '7h'
}

item{
    id: 7
    name: '8h'
}

item{
    id: 8
    name: '9h'
}

item{
    id: 9
    name: '10h'
}

item{
    id: 10
    name: 'jh'
}

item{
    id: 11
    name: 'qh'
}

item{
    id: 12
    name: 'kh'
}

item{
    id: 13
    name: 'ah'
}

item{
    id: 14
    name: '2d'
}

item{
    id: 15
    name: '3d'
}

item{
    id: 16
    name: '4d'
}

item{
    id: 17
    name: '5d'
}

item{
    id: 18
    name: '6d'
}

item{
    id: 19
    name: '7d'
}

item{
    id: 20
    name: '8d'
}

item{
    id: 21
    name: '9d'
}

item{
    id: 22
    name: '10d'
}

item{
    id: 23
    name: 'jd'
}

item{
    id: 24
    name: 'qd'
}

item{
    id: 25
    name: 'kd'
}

item{
    id: 26
    name: 'ad'
}

item{
    id: 27
    name: '2c'
}

item{
    id: 28
    name: '3c'
}

item{
    id: 29
    name: '4c'
}

item{
    id: 30
    name: '5c'
}

item{
    id: 31
    name: '6c'
}

item{
    id: 32
    name: '7c'
}

item{
    id: 33
    name: '8c'
}

item{
    id: 34
    name: '9c'
}

item{
    id: 35
    name: '10c'
}

item{
    id: 36
    name: 'jc'
}

item{
    id: 37
    name: 'qc'
}

item{
    id: 38
    name: 'kc'
}

item{
    id: 39
    name: 'ac'
}

item{
    id: 40
    name: '2s'
}

item{
    id: 41
    name: '3s'
}

item{
    id: 42
    name: '4s'
}

item{
    id: 43
    name: '5s'
}

item{
    id: 44
    name: '6s'
}

item{
    id: 45
    name: '7s'
}

item{
    id: 46
    name: '8s'
}

item{
    id: 47
    name: '9s'
}

item{
    id: 48
    name: '10s'
}

item{
    id: 49
    name: 'js'
}

item{
    id: 50
    name: 'qs'
}

item{
    id: 51
    name: 'ks'
}

item{
    id: 52
    name: 'as'
}
